version: '3.7'

services:
    node:
        build:
            context: ./
            dockerfile: ./docker/dockerfile
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000